#!/bin/bash -e
#
# S2I assemble script for the 'book-custom-s2i' image.
# The 'assemble' script currently only supports binary builds.
#
# For more information refer to the documentation:
#    https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#
if [ ! -z ${S2I_DEBUG} ]; then
	echo "turning on assembly debug";
  set -x
fi

ls -ltr /opt/app

chmod +x -R /opt/app

ls -ltr /opt/app/src

# Binary deployment is a single war
#if [ $(ls /opt/app/src/*.jar | wc -l) -eq 1 ]; then
  
  # mkdir -p /opt/app/deployment
  
#  mv /opt/app/src/*.jar service-server.jar

# else
#  echo "Jar not found in /opt/app/src"
#  exit 1
# fi
